### ISSUE TITLE
Consider pinning `avr-hal` revision in dev-dependencies

### ISSUE THREAD

**Issue by Rahix** [Cryptjar/avr-progmem-rs#1]
Hey!

You should probably pin the version of `avr-hal` in the dev-dependencies to a specific git revision.  `avr-hal` is still quite early in development and newer versions might break the example code so this way anyone downloading the project and trying to compile the example in the future will build against the same version of `avr-hal` that you originally wrote it for:

```toml
[dev-dependencies.arduino-uno]
# It is not yet available via crates.io
git = "https://github.com/Rahix/avr-hal.git"
rev = "7337cd76cd96f2d27701b137396d94a06d3a501d"
```

([`7337cd76cd96`](https://github.com/Rahix/avr-hal/commit/7337cd76cd96f2d27701b137396d94a06d3a501d) is the latest commit on master, you should probably check whether that still works and use an older rev instead if it does not ...)
